<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<jsp:include page="./_header.jsp"></jsp:include>
            <section id="admin-index">
                <nav>
                    <h3>관리자 메인</h3>
                    <p>
                        HOME >
                        <strong>메인</strong>
                    </p>
                </nav>
                <h4>쇼핑몰 운영현황</h4>
                <article>
                    <table>
                        <tr>
                            <td>
                                <strong>주문건수(건)</strong>
                                <span>${vo.totalOrdNo}</span>
                            </td>
                            <td>
                                <strong>주문금액(원)</strong>
                                <span>${vo.totalOrdPrice}</span>
                            </td>
                            <c:if test="${sessUser.level eq 7}">
                            <td>
                                <strong>회원가입(명)</strong>
                                <span>${vo.uid}</span>
                            </td>
                            <td>
                                <strong>쇼핑몰 방문(명)</strong>
                                <span>0</span>
                            </td>
                            <td>
                                <strong>신규게시물(건)</strong>
                                <span>${vo.totalProd}</span>
                            </td>
                            </c:if>
                        </tr>
                        <tr>
                            <td>
                                <p>
                                    <span>PC</span>
                                    <span>${vo.totalOrdNo}</span>
                                </p>
                                <p>
                                    <span>Mobile</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <td>
                                <p>
                                    <span>PC</span>
                                    <span>${vo.totalOrdPrice}</span>
                                </p>
                                <p>
                                    <span>Mobile</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <c:if test="${sessUser.level eq 7}">
                            <td>
                                <p>
                                    <span>PC</span>
                                    <span>${vo.uid}</span>
                                </p>
                                <p>
                                    <span>Mobile</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <td>
                                <p>
                                    <span>PC</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>Mobile</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <td>
                                <p>
                                    <span>PC</span>
                                    <span>${vo.totalProd}</span>
                                </p>
                                <p>
                                    <span>Mobile</span>
                                    <span>0</span>
                                </p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>
                                    <span>어제</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>주간</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>월간</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <td>
                                <p>
                                    <span>어제</span>
                                    <span></span>
                                </p>
                                <p>
                                    <span>주간</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>월간</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <td>
                                <p>
                                    <span>어제</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>주간</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>월간</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <td>
                                <p>
                                    <span>어제</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>주간</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>월간</span>
                                    <span>0</span>
                                </p>
                            </td>
                            <td>
                                <p>
                                    <span>어제</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>주간</span>
                                    <span>0</span>
                                </p>
                                <p>
                                    <span>월간</span>
                                    <span>0</span>
                                </p>
                            </td>
                            </c:if>
                        </tr>
                    </table>
                </article>
                <h4>주문 업무현황</h4>
                <article>
                    <table>
                        <tr>
                            <td>
                                <strong>입금대기(건)</strong>
                                <span>100</span>
                            </td>
                            <td>
                                <strong>배송준비(건)</strong>
                                <span>100</span>
                            </td>
                            <td>
                                <strong>취소요청(건)</strong>
                                <span>100</span>
                            </td>
                            <td>
                                <strong>교환요청(건)</strong>
                                <span>100</span>
                            </td>
                            <td>
                                <strong>반품요청(건)</strong>
                                <span>100</span>
                            </td>
                        </tr>
                    </table>
                </article>

                <div>
                    <div>
                        <h4>공지사항</h4>
                        <article>
                        	<c:forEach var="notice" items="${index.notice}" end="4">
                            <p>
                                <span>
                                    [${notice.cateType2}]
                                    ${notice.title}
                                </span>
                                <span class="noticeDate">
                                	<fmt:parseDate value="${notice.rdate}" var="time" pattern="yyyy-MM-dd HH:mm:ss"/>
	                            	<fmt:formatDate value="${time}" pattern="yy.MM.dd"/> 
                                </span>
                            </p>
                            </c:forEach>
                        </article>
                    </div>
                    <div>
                        <h4>고객문의</h4>
                        <article>
                        	<c:forEach var="qna" items="${index.qna}" end="4">
                            <p>
                                <span>
                                    [${qna.cateType2}]
                                    ${qna.title}
                                </span>
                                <span class="uid">${qna.uid.substring(0,3)}**</span>
                                <span>
                                	<fmt:parseDate value="${qna.rdate}" var="time" pattern="yyyy-MM-dd HH:mm:ss"/>
	                            	<fmt:formatDate value="${time}" pattern="yy.MM.dd"/> 
                                </span>
                            </p>
                            </c:forEach>
                        </article>
                    </div>
                </div>
            </section>
        </main>
<jsp:include page="./_footer.jsp"></jsp:include>